name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure lib CMake
      run: INSTALL_DIR=${{github.workspace}}/artifacts cmake -B ${{github.workspace}}/build-shared -DSOME_HASH_INSTALL=ON -DSOME_HASH_BUILD_TESTS=ON -DSOME_HASH_BUILD_EXAMPLES=ON

    - name: Build lib
      run: cmake --build ${{github.workspace}}/build-shared
      
    - name: Install lib
      run: cmake --install ${{github.workspace}}/build-shared

    - name: Test lib
      working-directory: ${{github.workspace}}/build-shared
      run: ctest
      
#--------------------------------------------------------------------------------------
# ARTIFACTS
#--------------------------------------------------------------------------------------
    - name: Prepare artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ${{github.workspace}}/artifacts
        if-no-files-found: error
        retention-days: 5
